### ISSUE TITLE
metadata.namespace not injected for manual resources

### ISSUE THREAD

**Issue by ankon** [Collaborne/kubernetes-bootstrap#4]
Assuming a resource manifest has:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: manual-job
  annotations:
    bootstrap.k8s.collaborne.com/manual: "true"
...
```

kubernetes-bootstrap should adjust the manifest in the output to have `metadata.namesapce` set, regardless of whether the resource is intended for manual execution. This would avoid issues where the operator misses to provide the `--namespace` argument to `kubectl apply` when actually applying the resource.
